name: CI pipeline Execution

on:
  push
jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      -name: checkout code
      uses: actions/checkout@v3

      -name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version:'3.10' 
        
      -name: install dependencies
      runs: |
        pip install -r requirements.txt

      -name: run pipeline
      env:
        DAGSHUB_PATH:${{secrets.DAGSHUB_PATH}}
      runs:
        dvc repro
